version: "3"

services:
  app:
    container_name: grepmatch
    build: .
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html/
    extra_hosts: # <--- this is required
      - "host.docker.internal:host-gateway" # <--- this is required
  db: 
    container_name: db_grepmatch
    image: mysql:8.1
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: secret
      MYSQL_USER: dummyuser
    volumes:
      - ./bin/mysql:/var/lib/mysql
    depends_on:
      - app